# Generated by Django 5.0 on 2023-12-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwords',
        ),
    ]
