# Generated by Django 5.0 on 2023-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=100, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+2348109545948', max_length=100, verbose_name='phone'),
        ),
    ]
